### ISSUE TITLE
Android Basics: xml-layouts / switch

### ISSUE THREAD

**Issue by Productivix** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#118]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-xml-layouts?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-xml-layouts#5

**In which task and step of the codelab can this issue be found?**
Complete the rest of the layout > Add a Switch for rounding up the tip

**Describe the problem**

the switch is no longer recommanded : see error :
![Capture](https://user-images.githubusercontent.com/6737060/114672155-1bb24f80-9d05-11eb-9af3-52983208f31e.PNG)

**Steps to reproduce?**
follwing the description 

2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 4.1.3 march 11
_API version of the emulator:_ 
no use

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
Thank you for reporting this issue. Use the following switch from the material library.

```
 <com.google.android.material.switchmaterial.SwitchMaterial
            android:id="@+id/round_up_switch"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:checked="true"
            android:text="@string/round_up_tip"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="@id/tip_options"
            app:layout_constraintTop_toBottomOf="@id/tip_options" />
```

The same has been updated in the codelab and will be published soon.

**Comment by Productivix** [comment]
hi, 
I corrected but , no design available and 2 errors :
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at android.content.res.BridgeTypedArray.getType(BridgeTypedArray.java:1024)
	at android.content.res.BridgeTypedArray.getType(BridgeTypedArray.java:809)
	at android.content.res.BridgeTypedArray.getValue(BridgeTypedArray.java:778)
	at android.content.res.BridgeTypedArray.peekValue(BridgeTypedArray.java:847)
	at android.view.View.<init>(View.java:5951)
	at android.view.ViewGroup.<init>(ViewGroup.java:697)
	at android.widget.FrameLayout.<init>(FrameLayout.java:99)
	at com.android.layoutlib.bridge.MockView.<init>(MockView.java:55)
	at com.android.layoutlib.bridge.MockView.<init>(MockView.java:51)
	at com.android.layoutlib.bridge.MockView.<init>(MockView.java:47)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:324)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1121)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1095)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:325)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:369)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:141)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:710)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$6(RenderTask.java:865)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$2.run(RenderExecutor.kt:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

and 
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at android.view.BridgeInflater.lambda$createViewFromCustomInflater$0(BridgeInflater.java:259)
	at android.view.BridgeInflater.createViewFromCustomInflater(BridgeInflater.java:285)
	at android.view.BridgeInflater.onCreateView(BridgeInflater.java:122)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:928)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:948)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1002)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:309)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1121)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1095)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:325)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:369)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:141)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:710)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$6(RenderTask.java:865)
	at com.android.tools.idea.rendering.RenderExecutor$runAsyncActionWithTimeout$2.run(RenderExecutor.kt:174)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at android.content.res.BridgeTypedArray.getType(BridgeTypedArray.java:1024)
	at android.content.res.BridgeTypedArray.getType(BridgeTypedArray.java:809)
	at android.content.res.BridgeTypedArray.getValue(BridgeTypedArray.java:778)
	at android.content.res.BridgeTypedArray.peekValue(BridgeTypedArray.java:847)
	at android.view.View.<init>(View.java:5951)
	at android.widget.TextView.<init>(TextView.java:996)
	at android.widget.EditText.<init>(EditText.java:87)
	at android.widget.EditText.<init>(EditText.java:83)
	at androidx.appcompat.widget.AppCompatEditText.<init>(AppCompatEditText.java:74)
	at androidx.appcompat.widget.AppCompatEditText.<init>(AppCompatEditText.java:69)
	at androidx.appcompat.app.AppCompatViewInflater.createEditText(AppCompatViewInflater.java:209)
	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:127)
	... 27 more
