### ISSUE TITLE
Android Basics issue: Writing Your First Instrumentation Test : Unit2 Layout

### ISSUE THREAD

**Issue by ShahsTestingZone** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#281]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**
Section 4

**Describe the problem**
Solution code shows error on my device. I was using my old codelab project. The error does not help. 
What i found to resolve the issue was  to add the closeSoftKeyboard() function after text input. 

    fun calculate_20_percent_tip() {

        onView(withId(R.id.cost_of_service_edit_text))
            .perform(typeText("50.00"))

         closeSoftKeyboard()

        onView(withId(R.id.calculate_button))
            .perform(click())

        onView(withId(R.id.tip_result))
            .check(matches(withText(containsString("Tip Amount: £10.00"))))
    }

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...
01-14 12:44:32.459 +0000  1000  1
androidx.test.espresso.PerformException: Error performing 'single click' on view 'view.getId() is <2131230820/shahjalom1990.example.tippingcalculator:id/calculate_button>'.
	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:1)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:9)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:4)
	at shahjalom1990.example.tippingcalculator.CalculatorTest.calculate_20_percent_tip(CalculatorTest.kt:38)
	... 29 trimmed
Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() covers at least <90> percent of the view's area)
Target view: "MaterialButton{id=2131230820, res-name=calculate_button, visibility=VISIBLE, width=984, height=144, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@e012ba6, tag=null, root-is-layout-requested=false, has-input-connection=false, x=48.0, y=1231.0, text=Calculate, input-type=0, ime-target=false, has-links=false, is-checked=false}"
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:20)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Versions**
_Android Studio version:_ Android Studio Arctic Fox | 2020.3.1 Patch 4
_API version of the emulator/Device: 31

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@ShahsTestingZone 
Thank you for reaching out to us. As one of the solutions is to add `.perform(ViewActions.closeSoftKeyboard())` after which  the entire  instruction would look like the following:
![Screen Shot 2022-03-30 at 5 23 15 PM](https://user-images.githubusercontent.com/86437155/160951984-d6830a25-1067-454b-88bc-3a32b888acc7.png)
The codelab content is updated and will be published soon.
