### ISSUE TITLE
Android Basics issue: Write Instrumentation Tests

### ISSUE THREAD

**Issue by gasti-jm** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#310]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#7

**In which task and step of the codelab can this issue be found?**
In step 4.

**Describe the problem**
When running the test, it crashes at runtime after writing "50.00" in the EditText called "cost_of_service_edit_text"

It seems that the error comes only from this line:
`onView(withId(R.id.calculate_button)).perform(click())`

I followed the steps to perfection and I have the code of "CalculatorTests.kl" exactly the same as the codelab.
Also try your code uploaded on GitHub in addition to the same tip time application. I have no idea how to solve this problem, I don't know if it will be due to some change in the Espresso.

The error code is the following:
`androidx.test.espresso.PerformException: Error performing 'single click' on view 'view.getId() is <2131230820/com.example.tiptime:id/calculate_button>'.
at androidx.test.espresso.PerformException$Builder.build(PerformException.java:1)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:9)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:4)
at com.example.tiptime.CalculatorTests.calculate_default_tip(CalculatorTests.kt:27)
... 29 trimmed
Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() covers at least <90> percent of the view's area)
Target view: "MaterialButton{id=2131230820, res-name=calculate_button, visibility=VISIBLE, width=864, height=144, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@216417e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=168.0, y=975.0, text=CALCULATE, input-type=0, ime-target=false, has-links=false, is-checked=false}"
at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:20)
at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Steps to reproduce?**
1. Go to the "Tip Time" application or use the project uploaded on GitHub, add the class "CalculatorTests.kl" in "androidTests/Java" and in your package "com.example.tiptime"
2. Click on the arrows to run the test.
3. See error...

**Versions**
_Android Studio version:  Android Studio Bumblebee | 2021.1.1 Patch 2
Build #AI-211.7628.21.2111.8193401, built on February 17, 2022
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 12
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), org.intellij.plugins.markdown (211.7142.37)

_API version of the emulator: Nexus 5 with API 27

**Additional information**
Here one picture:

![problem](https://user-images.githubusercontent.com/82490615/155805056-fff5513d-d8c4-4b75-a1e0-60248fa5bf8e.png)

**Comment by Him-anshuSharma** [comment]
Hey, I faced the same issue .It seems Issue is there because the keyboard is still open. Try changing  this in the line where you give input to edit text view.

*onView(withId(*Edit text id*)).perform(typeText("text"))*
 
to

*onView(withId(*Edit text id*)).perform(typeText("text"), closeSoftKeyboard())*
